### PR TITLE
chore: reduce yaml dependencies footprint

### PR DESCRIPTION
**Pull request by andig**
## Description

Noticed that k8s suddenly appeared in my dependencies. Since this only adds yaml2json features it's not necessary here.

## Changes
- Replace sigs yaml deps by go-yaml

## Checklist
- [x] I have read the **CONTRIBUTING.md** document.
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I have updated the documentation accordingly.
- [ ] This change requires a change to the documentation on the website.

## Additional Information

Follow-up to https://github.com/go-sprout/sprout/pull/36

### CODE REVIEW

**Comment by andig** [comment]
I‘ll fix the tests

**Comment by 42atomys** [comment]
Hey, thanks for your time, dont hesitate to request review when you need !

**Comment by andig** [comment]
@42atomys please take a look. Formatting change due to `gofmt`.

Worth noting that all tests are failing locally:

```
--- FAIL: TestMustToDate (0.00s)
    --- FAIL: TestMustToDate/TestDate (0.00s)
        conversion_functions_test.go:143:
            	Error Trace:	/Users/andig/htdocs/sprout/test_helpers_test.go:57
            	Error:      	Not equal:
            	            	expected: "time.Time-2024-05-09 00:00:00 +0000 UTC"
            	            	actual  : "time.Time-2024-05-09 00:00:00 +0200 CEST"
```

Seems that the tests are not stable regarding time zone?

**Comment by 42atomys** [comment]
@andig I will takes a look to resolve the time zone leaking 💧 by opening an issue to track that (https://github.com/go-sprout/sprout/issues/41)

**Review by 42atomys — APPROVED** [review]
LGTM ✅ 

Thanks for your contribution and help us to follow the directives of "reducing dependencies" 💜

**Pull request merged**
